{{- if and (not .Values.cloudflare.existingSecret) (or .Values.cloudflare.apiToken .Values.cloudflare.accountId .Values.cloudflare.zoneId) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cf-tunnel-operator.fullname" . }}
  namespace: {{ include "cf-tunnel-operator.namespace" . }}
  labels:
    {{- include "cf-tunnel-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  CF_ACCOUNT_ID: {{ .Values.cloudflare.accountId | quote }}
  CF_ZONE_ID: {{ .Values.cloudflare.zoneId | quote }}
  CF_API_TOKEN: {{ .Values.cloudflare.apiToken | quote }}
{{- end }}
