apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cf-tunnel-operator.fullname" . }}
  namespace: {{ include "cf-tunnel-operator.namespace" . }}
  labels:
    {{- include "cf-tunnel-operator.labels" . | nindent 4 }}
